/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mamani;

import javax.swing.JComboBox;
import javax.swing.*;
import java.awt.*;
import java.net.URL;

import java.sql.Connection;
import java.sql.SQLException;

import mamani.ConexionBD.*;
/**
 *
 * @author Kiara
 */
public class busquedas extends javax.swing.JFrame {

    /**
     * Creates new form busquedas
     */
    private ConexionBD conexionBD; // Declarar la variable a nivel de la clase

    public busquedas() {
        initComponents();
        this.setTitle("SmartFit - Filtros");
         // Obtener la URL de la imagen
          URL imageURL = getClass().getResource("/mamani/Imagenes/Logo.jpg");
          System.out.println(imageURL);


          // Verificar si la URL se ha encontrado correctamente
      if (imageURL != null) {
          // Crear un ImageIcon a partir de la URL
          ImageIcon icono = new ImageIcon(imageURL);

          // Obtener la imagen desde el ImageIcon
          Image image = icono.getImage();

          // Establecer la imagen como ícono de la ventana
          this.setIconImage(image);
        conexionBD = new ConexionBD(); // Inicializar la instancia en el constructor
    }
    }    
    private void mostrarRecetas(String[] recetas) {
        menuesFiltros menuFiltros = new menuesFiltros();
        menuFiltros.actualizarRecetas(recetas);
        menuFiltros.setVisible(true); // Asegúrate de hacer visible la ventana
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BajaCaloriasBtn = new javax.swing.JButton();
        BajoEnGrasasBtn = new javax.swing.JButton();
        ProteicoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BUSCAR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Grasas");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 90, 60));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Calorias");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, 50));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Proteinas");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, 60));

        BajaCaloriasBtn.setText("Baja Calorias");
        BajaCaloriasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaCaloriasBtnActionPerformed(evt);
            }
        });
        jPanel2.add(BajaCaloriasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, 30));

        BajoEnGrasasBtn.setText("Bajo en Grasas");
        BajoEnGrasasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajoEnGrasasBtnActionPerformed(evt);
            }
        });
        jPanel2.add(BajoEnGrasasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 110, 30));

        ProteicoBtn.setText("Proteico");
        ProteicoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProteicoBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ProteicoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BajaCaloriasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaCaloriasBtnActionPerformed
              
        try {
        // Obtener la conexión de la instancia de ConexionBD
        Connection conexion = conexionBD.obtenerConexion();
        String[] recetas = conexionBD.obtenerMenosGrasas(conexion); // Pasar la conexión como argumento
        mostrarRecetas(recetas);
    } catch (SQLException e) {
        e.printStackTrace();
    }

    }//GEN-LAST:event_BajaCaloriasBtnActionPerformed

    private void BajoEnGrasasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajoEnGrasasBtnActionPerformed
       try {
        Connection conexion = conexionBD.obtenerConexion();
        String[] recetas = conexionBD.obtenerMenosGrasas(conexion);
        mostrarRecetas(recetas);
    } catch (SQLException e) {
        e.printStackTrace();
    }       }//GEN-LAST:event_BajoEnGrasasBtnActionPerformed

    private void ProteicoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProteicoBtnActionPerformed
          try {
        Connection conexion = conexionBD.obtenerConexion();
        String[] recetas = conexionBD.obtenerProteico(conexion);
        mostrarRecetas(recetas);
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_ProteicoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busquedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busquedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busquedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busquedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new busquedas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BajaCaloriasBtn;
    private javax.swing.JButton BajoEnGrasasBtn;
    private javax.swing.JButton ProteicoBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
